{
 "title": "Prometheus Nomad",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Nomad Client Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_client_allocated_memory" }
   ]
  },
  {
   "title": "Nomad Client Host Memory Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_memory_available"
    }
   ]
  },
  {
   "title": "Client Consul Check Registrations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_client_consul_check_registrations"
    }
   ]
  },
  {
   "title": "Client Allocations Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_linux_client_allocations_running"
    }
   ]
  },
  {
   "title": "Client Allocations Blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_linux_client_allocations_blocked"
    }
   ]
  },
  {
   "title": "Runtime Total GS Pauses",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "nomad_linux_runtime_total_gc_pause_ns"
    }
   ]
  },
  {
   "title": "Runtime Alloc Bytes (Linux)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_linux_runtime_alloc_bytes"
    }
   ]
  }
 ]
}