FROM grafana/grafana

COPY datasources.yaml      /etc/grafana/provisioning/datasources/
COPY dashboard_config.yaml /etc/grafana/provisioning/dashboards/
COPY dashboard_cos.json    /var/lib/grafana/dashboards/
