FROM grafana/grafana

COPY datasources.yaml      /etc/grafana/provisioning/datasources/datasources.yaml
COPY dashboard_config.yaml /etc/grafana/provisioning/dashboards/config.yaml
COPY dashboard_cos.json   /var/lib/grafana/dashboards/cos.json
