@startuml

package "networking-stack"{
  [vpc, subnets,\nacl, routes] as BNW
  [peering]
  [dns,\ningress alb\ningress alb-sg] as INGR
}

package "cos-stack"{
  [**consul**] as CS
  [**ui-access:**\ndns,\nui alb's,\nui alb-attachment,\n ui alb-targetgroup] as UI
  [**nomad:**\ningress alb-attachment,\n ingress-alb-targetgroup] as NM
  [**nomad-datacenter**] as DC
}

NM --> BNW
CS --> BNW
UI --> BNW
UI --> NM: ASG of\nnomad-servers\nand -clients
UI --> CS: ASG of\nconsul-servers
DC --> NM: SG of Nomad Server
DC --> BNW
DC --> INGR: ARN of ingress alb

@enduml