@startuml

package "networking-stack"{
  [vpc, subnets,\nacl, routes] as BNW
  [peering]
  [dns,\ningress alb\ningress alb-sg] as INGR
}

package "cos-stack"{
  [**consul**] as CS
  [**ui-access:**\nproxy, dns,\nui alb's,\nui alb-attachment,\n ui alb-targetgroup] as UI
  [**nomad:**\ningress alb-attachment,\n ingress-alb-targetgroup] as NM
  [**vars:**\nconsul_cluster_name] as VARS
}

NM --> BNW
NM --> INGR
CS --> BNW
UI --> BNW
UI --> NM: ASG of\nnomad-servers\nand -clients
UI --> CS: ASG of\nconsul-servers
CS --> VARS: consul_cluster_name
NM --> VARS: consul_cluster_name

@enduml