 version: 2
 jobs:
   build:
     working_directory: /go/src/github.com/MatthiasScholz/cos/
     docker:
       - image: circleci/golang:1.14.2
     steps:
       - checkout
       - run:
           working_directory: /go/src/github.com/MatthiasScholz/cos/test
           command: make all
