FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4


#################################################
# NOTE: The following lines can keep untouched. #
#################################################
ARG   VERSION=unknown
LABEL version=$VERSION
COPY  version /IMAGE_VERSION
